embed_model: zhipu-embedding-3
enable_knowledge_base: true
enable_knowledge_graph: true
enable_reranker: true
enable_search_engine: false
filename: src/saves\config\config.yaml
model_local_paths:
  bge-reranker-v2-m3: local/BAAI--bge-reranker-v2-m3/snapshots/953dc6f6f85a1b2dbfca4c34a2796e7dde08d41e
model_name: deepseek-chat
model_provider: deepseek
reranker: bge-reranker-v2-m3
save_dir: src/saves
stream: true
valuable_model_provider:
- openai
- deepseek
- zhipu
- dashscope
- siliconflow
